### ISSUE TITLE
Show only violations in output

### ISSUE THREAD

**Issue by blablatdinov** [blablatdinov/ondivi#48]
Some tools out too much lines (pylint). Ondivi must show only violations without other messages

Actual:

```
$ pylint file.py | ondivi
************* Module file
file.py:12:0: C0301: Line too long (119/100) (line-too-long)

------------------------------------------------------------------
```

Expected:

```
$ pylint file.py | ondivi
file.py:12:0: C0301: Line too long (119/100) (line-too-long)
```

**Comment by 0pdd** [comment]
@blablatdinov the puzzle [#50](https://github.com/blablatdinov/ondivi/issues/50) is still not solved.

**Comment by 0pdd** [comment]
@blablatdinov the only puzzle [#50](https://github.com/blablatdinov/ondivi/issues/50) is solved here.
