### ISSUE TITLE
Support black and isort

### ISSUE THREAD

**Issue by supadrupa** [blablatdinov/ondivi#94]
Amazing program can you add support `black --check` and `isort -c`?

**Comment by blablatdinov** [comment]
@supadrupa Hi! Thanks for report!

Great idea, I'll try to implement it

**Comment by blablatdinov** [comment]
@supadrupa I created an [PR](#95). Unfortunately, `black --check` show only file names without line numbers, so "ondivi" filter out lines only by the file name

`black --check` output:

```
would reformat ondivi/__main__.py
would reformat file.py

Oh no! 💥 💔 💥
1 file would be reformatted.
```

`black --check | ondivi` output:

```
would reformat file.py

Oh no! 💥 💔 💥
1 file would be reformatted.
```

Is this what you expect?

**Comment by supadrupa** [comment]
@blablatdinov Yes, I think this is what is needed.

**Comment by blablatdinov** [comment]
@supadrupa I research the use of black and isort for modified files and found a method that does not require changes to ondivi.

You can use `git diff --name-only` command

`black --check $(git diff --name-only)` or `isort -c $(git diff --name-only)`

Also check `flake8-black` or `flake8-isort` tools for convert black or isort issues to flake8 format
